name: HC's personal site(trial)
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
highlighter: rouge
encoding: bom|utf-8

title:            Scribble
url:              https://hencychine.github.io # Site url, without a slash at the end.
signoff:          Hency Chine
disqus_shortname: HencyChine # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://github.com/hencychine
    external:     true
  - name:         GitHub
    url:          http://github.com/hencychine
    external:     true

# permalink:        pretty
# markdown:         redcarpet
# redcarpet:
#  extensions:
#    - smart
